LANGUAGE_CHOICES = (
    ("Polski", "Polski"),
    ("Angielski", "Angielski"),
    ("Hiszpański", "Hiszpański"),
    ("Niemiecki", "Niemiecki"),
    ("Francuski", "Francuski"),
    ("Włoski", "Włoski"),
    ("Portugalski", "Portugalski"),
    ("Holenderski", "Holenderski"),
    ("Rosyjski", "Rosyjski"),
    ("Chiński", "Chiński"),
    ("Japoński", "Japoński"),
    ("Koreański", "Koreański"),
    ("Arabski", "Arabski"),
    ("Turecki", "Turecki"),
    ("Grecki", "Grecki"),
    ("Szwedzki", "Szwedzki"),
    ("Norweski", "Norweski"),
    ("Duński", "Duński"),
    ("Finski", "Finski"),
    ("Islandzki", "Islandzki"),
    ("Słowacki", "Słowacki"),
    ("Czeski", "Czeski"),
    ("Słoweński", "Słoweński"),
    ("Węgierski", "Węgierski"),
    ("Rumuński", "Rumuński"),
    ("Bułgarski", "Bułgarski"),
    ("Ukraiński", "Ukraiński"),
    ("Litewski", "Litewski"),
    ("Łotewski", "Łotewski"),
    ("Estoński", "Estoński"),
    ("Białoruski", "Białoruski"),
    ("Chorwacki", "Chorwacki"),
    ("Serbski", "Serbski"),
    ("Macedoński", "Macedoński"),
    ("Albański", "Albański"),
    ("Szwajcarski", "Szwajcarski"),
    ("Irlandzki", "Irlandzki"),
    ("Szkocki", "Szkocki"),
    ("Walijski", "Walijski"),
    ("Angielski amerykański", "Angielski amerykański"),
    ("Kanadyjski", "Kanadyjski"),
    ("Meksykański", "Meksykański"),
    ("Brazylijski", "Brazylijski"),
    ("Argentyński", "Argentyński"),
    ("Chiński tradycyjny", "Chiński tradycyjny"),
    ("Chiński uproszczony", "Chiński uproszczony"),
    ("Japoński tradycyjny", "Japoński tradycyjny"),
    ("Japoński uproszczony", "Japoński uproszczony"),
)


LANGUAGE_LEVEL_CHOICES = (
    ("Master", "Master"),
    ("Fluent", "Fluent"),
    ("Advanced", "Advanced"),
    ("Intermediate", "Intermediate"),
    ("Beginner", "Beginner"),
)


JOBS = (
    ("Nauczyciel", "Nauczyciel"),
    ("Lekarz", "Lekarz"),
    ("Inżynier", "Inzynier"),
    ("Prawnik", "Prawnik"),
    ("Sprzedawca", "Sprzedawca"),
    ("Programista", "Programista"),
    ("Księgowy", "Ksiegowy"),
    ("Projektant graficzny", "Projektant graficzny"),
    ("Pilot", "Pilot"),
    ("Architekt", "Architekt"),
    ("Polityk", "Polityk"),
    ("Dziennikarz", "Dziennikarz"),
    ("Psycholog", "Psycholog"),
    ("Chemik", "Chemik"),
    ("Fizjoterapeuta", "Fizjoterapeuta"),
    ("Fotograf", "Fotograf"),
    ("Instruktor fitness", "Instruktor fitness"),
    ("Mechanik samochodowy", "Mechanik samochodowy"),
    ("Projektant mody", "Projektant mody"),
    ("Kucharz", "Kucharz"),
    ("Ogrodnik", "Ogrodnik"),
    ("Elektryk", "Elektryk"),
    ("Muzyk", "Muzyk"),
    ("Tłumacz", "Tlumacz"),
    ("Hydraulik", "Hydraulik"),
    ("Kierowca ciężarówki", "Kierowca ciezarowki"),
    ("Geolog", "Geolog"),
    ("Projektant wnętrz", "Projektant wnetrz"),
    ("Strażak", "Strazak"),
    ("Bibliotekarz", "Bibliotekarz"),
    ("Weterynarz", "Weterynarz"),
    ("Trener personalny", "Trener personalny"),
    ("Aktor", "Aktor"),
    ("Projektant gier komputerowych", "Projektant gier komputerowych"),
    ("Farmaceuta", "Farmaceuta"),
    ("Projektant dźwięku", "Projektant dzwieku"),
    ("Doradca finansowy", "Doradca finansowy"),
    ("Barista", "Barista"),
    ("Właściciel restauracji", "Wlasciciel restauracji"),
    ("Lotnik", "Lotnik"),
    ("Projektant produktu", "Projektant produktu"),
    ("Copywriter", "Copywriter"),
    ("Tancerz", "Tancerz"),
    ("Doradca zawodowy", "Doradca zawodowy"),
    ("Grafik komputerowy", "Grafik komputerowy"),
    ("Analityk danych", "Analityk danych"),
    ("Stewardessa", "Stewardessa"),
    ("Animator", "Animator"),
    ("Fotoreporter", "Fotoreporter"),
    ("Pracownik socjalny", "Pracownik socjalny"),
    ("Geodeta", "Geodeta"),
    ("Notariusz", "Notariusz"),
    ("Filmowiec", "Filmowiec"),
    ("Mechanik lotniczy", "Mechanik lotniczy"),
)
