# Generated by Django 4.2.1 on 2023-05-23 08:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import match_job_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("available_from", models.CharField(max_length=50, null=True)),
                ("available_to", models.CharField(max_length=50, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="default.jpeg",
                        null=True,
                        upload_to=match_job_app.models.employee_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"]
                            )
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("company_address", models.CharField(max_length=200, null=True)),
                ("company_description", models.TextField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "company_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=match_job_app.models.employer_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                ("requirements", models.TextField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="match_job_app.employer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_name",
                    models.CharField(
                        choices=[
                            ("Polski", "Polski"),
                            ("Angielski", "Angielski"),
                            ("Hiszpański", "Hiszpański"),
                            ("Niemiecki", "Niemiecki"),
                            ("Francuski", "Francuski"),
                            ("Włoski", "Włoski"),
                            ("Portugalski", "Portugalski"),
                            ("Holenderski", "Holenderski"),
                            ("Rosyjski", "Rosyjski"),
                            ("Chiński", "Chiński"),
                            ("Japoński", "Japoński"),
                            ("Koreański", "Koreański"),
                            ("Arabski", "Arabski"),
                            ("Turecki", "Turecki"),
                            ("Grecki", "Grecki"),
                            ("Szwedzki", "Szwedzki"),
                            ("Norweski", "Norweski"),
                            ("Duński", "Duński"),
                            ("Finski", "Finski"),
                            ("Islandzki", "Islandzki"),
                            ("Słowacki", "Słowacki"),
                            ("Czeski", "Czeski"),
                            ("Słoweński", "Słoweński"),
                            ("Węgierski", "Węgierski"),
                            ("Rumuński", "Rumuński"),
                            ("Bułgarski", "Bułgarski"),
                            ("Ukraiński", "Ukraiński"),
                            ("Litewski", "Litewski"),
                            ("Łotewski", "Łotewski"),
                            ("Estoński", "Estoński"),
                            ("Białoruski", "Białoruski"),
                            ("Chorwacki", "Chorwacki"),
                            ("Serbski", "Serbski"),
                            ("Macedoński", "Macedoński"),
                            ("Albański", "Albański"),
                            ("Szwajcarski", "Szwajcarski"),
                            ("Irlandzki", "Irlandzki"),
                            ("Szkocki", "Szkocki"),
                            ("Walijski", "Walijski"),
                            ("Angielski amerykański", "Angielski amerykański"),
                            ("Kanadyjski", "Kanadyjski"),
                            ("Meksykański", "Meksykański"),
                            ("Brazylijski", "Brazylijski"),
                            ("Argentyński", "Argentyński"),
                            ("Chiński tradycyjny", "Chiński tradycyjny"),
                            ("Chiński uproszczony", "Chiński uproszczony"),
                            ("Japoński tradycyjny", "Japoński tradycyjny"),
                            ("Japoński uproszczony", "Japoński uproszczony"),
                        ],
                        default="Polski",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Master", "Master"),
                            ("Fluent", "Fluent"),
                            ("Advanced", "Advanced"),
                            ("Intermediate", "Intermediate"),
                            ("Beginner", "Beginner"),
                        ],
                        default="MASTER",
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "language_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language",
                        to="match_job_app.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeJobTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_name", models.CharField(max_length=300)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="match_job_app.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=200, null=True)),
                (
                    "job_expirience",
                    models.CharField(
                        choices=[
                            (1, "Mniej niż sześć miesięcy"),
                            (2, "Rok"),
                            (3, "Rok - 3 lata"),
                            (4, "3 lata - 5 lat"),
                            (5, "Powyżej 5 lat"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("work_from", models.CharField(max_length=50, null=True)),
                ("work_to", models.CharField(max_length=50, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "job_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="match_job_app.employee",
                    ),
                ),
            ],
        ),
    ]
