# Generated by Django 4.2.1 on 2023-05-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("match_job_app", "0003_rename_job_employeejob_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeejob",
            name="experience",
        ),
        migrations.AddField(
            model_name="employeejob",
            name="description",
            field=models.TextField(default="abcd"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeejob",
            name="work_from",
            field=models.DateField(default="2000-12-02"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="available_from",
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="available_to",
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeejob",
            name="job_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="match_job_app.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeelanguage",
            name="language_name",
            field=models.CharField(
                choices=[("PL", "Polish"), ("ENG", "English")],
                default="PL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employeelanguage",
            name="language_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language",
                to="match_job_app.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeelanguage",
            name="level",
            field=models.CharField(
                choices=[("MASTER", "MASTER"), ("BSIC", "BASIC")],
                default="MASTER",
                max_length=100,
            ),
        ),
    ]
