# Generated by Django 4.2.1 on 2023-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match_job_app", "0005_alter_employeejob_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="available_from",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="available_to",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeejob",
            name="work_from",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
