# Generated by Django 4.2.1 on 2023-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match_job_app", "0007_employeejob_work_to_alter_employeejob_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="employeelanguage",
            name="language_name",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("nl", "Dutch"),
                    ("sv", "Swedish"),
                    ("fi", "Finnish"),
                    ("da", "Danish"),
                    ("no", "Norwegian"),
                    ("ro", "Romanian"),
                    ("cs", "Czech"),
                    ("hu", "Hungarian"),
                    ("bg", "Bulgarian"),
                    ("el", "Greek"),
                    ("et", "Estonian"),
                    ("lt", "Lithuanian"),
                    ("lv", "Latvian"),
                    ("hr", "Croatian"),
                    ("sl", "Slovenian"),
                    ("sk", "Slovak"),
                    ("ga", "Irish"),
                    ("mt", "Maltese"),
                    ("cy", "Welsh"),
                    ("gd", "Scottish Gaelic"),
                    ("sq", "Albanian"),
                    ("mk", "Macedonian"),
                    ("sr", "Serbian"),
                    ("bs", "Bosnian"),
                    ("is", "Icelandic"),
                    ("fy", "Frisian"),
                    ("af", "Afrikaans"),
                    ("lb", "Luxembourgish"),
                    ("sq", "Albanian"),
                    ("mk", "Macedonian"),
                    ("sr", "Serbian"),
                    ("bs", "Bosnian"),
                    ("is", "Icelandic"),
                    ("fy", "Frisian"),
                    ("af", "Afrikaans"),
                    ("lb", "Luxembourgish"),
                    ("mt", "Maltese"),
                    ("be", "Belarusian"),
                    ("uk", "Ukrainian"),
                    ("ru", "Russian"),
                    ("ka", "Georgian"),
                    ("hy", "Armenian"),
                    ("lt", "Lithuanian"),
                    ("lv", "Latvian"),
                ],
                default="pl",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employeelanguage",
            name="level",
            field=models.CharField(
                choices=[
                    ("Master", "Master"),
                    ("Fluent", "Fluent"),
                    ("Advanced", "Advanced"),
                    ("Intermediate", "Intermediate"),
                    ("Beginner", "Beginner"),
                ],
                default="MASTER",
                max_length=100,
            ),
        ),
    ]
