# Generated by Django 4.2.1 on 2023-05-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_job_app', '0009_alter_employee_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeejob',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeejobtarget',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeelanguage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeejobtarget',
            name='target_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeelanguage',
            name='language_name',
            field=models.CharField(choices=[('Polski', 'Polski'), ('Angielski', 'Angielski'), ('Hiszpański', 'Hiszpański'), ('Niemiecki', 'Niemiecki'), ('Francuski', 'Francuski'), ('Włoski', 'Włoski'), ('Portugalski', 'Portugalski'), ('Holenderski', 'Holenderski'), ('Rosyjski', 'Rosyjski'), ('Chiński', 'Chiński'), ('Japoński', 'Japoński'), ('Koreański', 'Koreański'), ('Arabski', 'Arabski'), ('Turecki', 'Turecki'), ('Grecki', 'Grecki'), ('Szwedzki', 'Szwedzki'), ('Norweski', 'Norweski'), ('Duński', 'Duński'), ('Finski', 'Finski'), ('Islandzki', 'Islandzki'), ('Słowacki', 'Słowacki'), ('Czeski', 'Czeski'), ('Słoweński', 'Słoweński'), ('Węgierski', 'Węgierski'), ('Rumuński', 'Rumuński'), ('Bułgarski', 'Bułgarski'), ('Ukraiński', 'Ukraiński'), ('Litewski', 'Litewski'), ('Łotewski', 'Łotewski'), ('Estoński', 'Estoński'), ('Białoruski', 'Białoruski'), ('Chorwacki', 'Chorwacki'), ('Serbski', 'Serbski'), ('Macedoński', 'Macedoński'), ('Albański', 'Albański'), ('Szwajcarski', 'Szwajcarski'), ('Irlandzki', 'Irlandzki'), ('Szkocki', 'Szkocki'), ('Walijski', 'Walijski'), ('Angielski amerykański', 'Angielski amerykański'), ('Kanadyjski', 'Kanadyjski'), ('Meksykański', 'Meksykański'), ('Brazylijski', 'Brazylijski'), ('Argentyński', 'Argentyński'), ('Chiński tradycyjny', 'Chiński tradycyjny'), ('Chiński uproszczony', 'Chiński uproszczony'), ('Japoński tradycyjny', 'Japoński tradycyjny'), ('Japoński uproszczony', 'Japoński uproszczony')], default='Polski', max_length=50),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_job_app.employer')),
            ],
        ),
    ]
