# Generated by Django 4.2.1 on 2023-05-21 21:26

from django.db import migrations, models
import match_job_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_job_app', '0010_remove_employer_name_employee_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_pic',
            field=models.ImageField(blank=True, null=True, upload_to=match_job_app.models.employer_directory_path),
        ),
    ]
