# Generated by Django 4.2.1 on 2023-05-22 10:40

import django.core.validators
from django.db import migrations, models
import match_job_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('match_job_app', '0011_employer_company_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejob',
            name='job_expirience',
            field=models.CharField(choices=[(1, 'Mniej niż sześć miesięcy'), (2, 'Rok'), (3, 'Rok - 3 lata'), (4, '3 lata - 5 lat'), (5, 'Powyżej 5 lat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=match_job_app.models.employee_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_pic',
            field=models.ImageField(blank=True, null=True, upload_to=match_job_app.models.employer_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
